version: '3.8'

services:
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pwd 
      - POSTGRES_DB=database
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
