version: '3.8'

services:
  postgres:
    build: 
        context: .
        dockerfile: postgres/Dockerfile
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: mydb
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
